# Generated by Django 5.2.11 on 2026-02-26 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "proposed_budget",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(help_text="Duration in days"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("submission_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_score", models.PositiveIntegerField(blank=True, null=True)),
                ("client_note", models.TextField(blank=True, null=True)),
                ("is_winner", models.BooleanField(default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="competitions.competition",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        limit_choices_to={"role": "FREELANCER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "proposals_proposal",
                "ordering": ["-created_at"],
                "unique_together": {("competition", "freelancer")},
            },
        ),
        migrations.CreateModel(
            name="ProposalAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="proposal_attachments/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "db_table": "proposals_proposalattachment",
            },
        ),
        migrations.CreateModel(
            name="ProposalRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("revision_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "proposals_proposalrevision",
                "ordering": ["-revision_number"],
            },
        ),
    ]
