# Generated by Django 5.2.11 on 2026-02-26 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("COMPETITION_OPENED", "Competition Opened"),
                            ("PROPOSAL_RECEIVED", "Proposal Received"),
                            ("PROPOSAL_SCORED", "Proposal Scored"),
                            ("PROPOSAL_ACCEPTED", "Proposal Accepted"),
                            ("PROPOSAL_REJECTED", "Proposal Rejected"),
                            ("COMPETITION_CLOSED", "Competition Closed"),
                            ("QUESTION_ANSWERED", "Question Answered"),
                            ("WINNER_SELECTED", "Winner Selected"),
                            ("NEW_REVIEW", "New Review"),
                            (
                                "COMPETITION_DEADLINE_APPROACHING",
                                "Competition Deadline Approaching",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("related_competition_id", models.UUIDField(blank=True, null=True)),
                ("related_proposal_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
